name: S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEPLOY_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEPLOY_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: docs
          bucket: arn:aws:s3:::bookwormfood
          bucket-region: us-east-1
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'