import React, { useEffect } from "react";
// import useState from 'react-usestateref';
import "../css/scan.css";
import { useParams } from "react-router-dom";
import { useNavigate } from "react-router-dom";
import initWasmModule, { get_book_data } from '../wasm-rust/isbn_mod.js';

export default function ScanResult() {

  const navigate = useNavigate();

  let { isbn } = useParams();

  // run the wasm initializer before calling wasm methods
  // the initializer is generated by wasm_pack
  (async () => {
    await initWasmModule();
    // hello_wasm(); // this call logs a hello message from WASM for demo purposes
    // log_isbn(isbn); // a more involved demo call
    // request book data from WASM module
    // the responses are sent back as messages to the window object   
    await get_book_data(isbn);
  })();

  useEffect(() => { }, []);

  // handles messages with book data sent back by the WASM module
  window.addEventListener("message", (msg) => {
    console.log(`WASM msg: ${msg.data} / ${msg.origin} / ${msg.source}`);

    // WASM messages should be JSON objects
    let data;
    try {
      data = JSON.parse(msg.data);
    }
    catch (e) {
      // use this for debugging, but this mostly logs messages sent from React tooling
      // in development mode, not sure it's worth logging this in production
      // console.log(`Error parsing JSON data: ${e}`);
      return;
    }

    // see `WasmResult` and `WasmResponse` in the WASM code for the structure of the data
    if (data?.googleBooks?.Ok) {
      let title = data.googleBooks.Ok?.items[0]?.volumeInfo?.title;
      console.log(`Title: ${title}`);
    }
  });

  const renderQrCodeResult = () => {
    return (
      <div>
        <p>ISBN: {isbn}</p>
        <p><a href={`https://www.goodreads.com/search?q=${isbn}`}>GoodReads</a> | <a href={`https://app.thestorygraph.com/browse?search_term=${isbn}`}>StoryGraph</a></p>
        <p><a href={`https://discover.aucklandlibraries.govt.nz/search?query=${isbn}`}>Auckland libraries</a></p>
        <p><a href={`https://www.google.com/search?tbo=p&tbm=bks&q=isbn:${isbn}`}>Google books</a></p>
        <p><a href={`https://www.thenile.co.nz/search?s.q=${isbn}`}>The Nile</a> | <a href={`https://www.amazon.com/s?k=${isbn}`}>Amazon</a> | <a href={`https://www.mightyape.co.nz/books?q=${isbn}`}>MightyApe</a></p>
      </div>)
  }
  const onClickBackHandler = (e) => {
    e.preventDefault();
    navigate(`/scan`)
  };

  const onClickCopyToClipboard = async (e) => {
    e.preventDefault();
    await navigator.clipboard.writeText(isbn);
    const btnId = document.getElementById("copyToClip");
    btnId.innerText = "DONE";
    btnId.style.backgroundColor = "green";
    setTimeout(() => {
      btnId.innerText = "COPY";
      btnId.style.backgroundColor = "";
    }, 1000);
  }

  const renderCopyToClipboardBtn = () => {
    return <a href="!#" style={{ padding: 12 }} id="copyToClip" className="myHref"
      onClick={onClickCopyToClipboard}>COPY ISBN</a>
  }

  const renderResult = () => {
    return (
      <div className="resultModal">
        <div className="result">
          {renderQrCodeResult()}
        </div>
        <div style={{ marginTop: 40 }}>
          <a href="!#" style={{ padding: 12 }} className="myHref" onClick={onClickBackHandler}>SCAN AGAIN</a>
          {renderCopyToClipboardBtn()}
        </div>
      </div>);
  };

  return (
    <div>
      {renderResult()}
    </div>
  )
};
